### ISSUE TITLE
LinkChangeListAdminField always uses ? and = in urls. Not working with Django Jet

### ISSUE THREAD

**Issue by stitch** [ebertti/django-admin-easy#14]
Hi,

Consider:
link1 = easy.LinkChangeListAdminField('organizations', 'organization', 'organization_id',
                                          {'id': 'organization_id'})

This renders as:
1, with a hyperlink to: http://localhost:8000/admin/organizations/organization/?id=1

Django jet rewrite urls, so they look more modern. This would be a valid URL in jet:
http://localhost:8000/admin/organizations/organization/1/change/

Result: The url created by LinkChangeListAdminField will not work in jet.

Regards,
Elger / Stitch

**Comment by stitch** [comment]
A workaround:

```
    @easy.with_tags()
    def link(self, obj):
        return '<a href="../../organizations/organization/{}/change">edit organization</a>'.format(obj.organization_id)

list_display = ('organization', 'link')
```

**Comment by ebertti** [comment]
Hi @stitch.

I you need to use another field to build a link for change view:

```python
link= easy.ForeignKeyAdminField('organization')
```
