### ISSUE TITLE
ImportError: No module named 'easy.admin.mixin'

### ISSUE THREAD

**Issue by leonty** [ebertti/django-admin-easy#5]
Hi, I only changed the version from 0.2.1 to 0.2.2 in my requirements.txt and got this:
> 	  File "/opt/crowd/crowd/promo/admin/__init__.py", line 1, in <module>
> 	    import easy
> 	  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/easy/__init__.py", line 7, in <module>
> 	    from .admin.mixin import MixinEasyViews
> 	ImportError: No module named 'easy.admin.mixin'

Environment:
Python 3.3.2 (default, Mar 10 2014, 09:51:20)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux

Update: same thing on Windows 8.1 Python 3.4.2

**Comment by ebertti** [comment]
Sorry for this error.

I really don't know is the best way to make the setup.py, and some times the release forget some files

I all ready fix it.

Relase 0.2.2.1 is on pypi

**Comment by ebertti** [comment]
See? I don't change anything and now is working.

**Comment by leonty** [comment]
Now it works, thanks!

btw, @easy.smart works for custom admin action methods too :)
